import { ITaskItem, PriorityEnum } from "@/types/taskTypes";
import { IPasswordItem } from "@/types/passwordTypes";

export const taskData: ITaskItem[] = Array.from({ length: 20 }, (_, i) => ({
  id: `${i + 1}`,
  title: `Task ${i + 1}`,
  description: `Description for Task ${i + 1}`,
  completed: i % 2 === 0,
  createdAt: new Date(),
  updatedAt: new Date(),
  tag: { key: "tag1", value: "工作" },
  completedAt: null,
  deletedAt: null,
  archivedAt: null,
  reminder: null,
  dueDate: new Date(),
  priority: [PriorityEnum.Low, PriorityEnum.Medium, PriorityEnum.High][i % 3],
}));

export const passwordsData: IPasswordItem[] = [
  {
    id: "1",
    name: "微信",
    icon: "wechat",
    username: "user@example.com",
    password: "MySecurePass123!",
    website: "https://weixin.qq.com",
    notes: "主要微信账号",
    createdAt: "2025-09-15",
    lastUsed: "2025-09-21",
    tag: { key: "tag1", value: "社交" },
  },
  {
    id: "2",
    name: "支付宝",
    icon: "alipay",
    username: "138****8888",
    password: "AlipayPass456@",
    website: "https://alipay.com",
    notes: "主要支付账号，绑定银行卡",
    createdAt: "2025-09-10",
    lastUsed: "2025-09-20",
    tag: { key: "tag2", value: "金融" },
  },
  {
    id: "3",
    name: "GitHub",
    icon: "github",
    username: "developer123",
    password: "GitHubSecure789#",
    website: "https://github.com",
    notes: "开发用GitHub账号",
    createdAt: "2025-09-05",
    lastUsed: "2025-09-21",
    tag: { key: "tag3", value: "工作" },
  },
  {
    id: "4",
    name: "网易云音乐",
    icon: "music",
    username: "music_lover",
    password: "MusicPass321$",
    website: "https://music.163.com",
    createdAt: "2025-08-28",
    lastUsed: "2025-09-19",
    tag: { key: "tag4", value: "娱乐" },
  },
];
